name: Mirror to gitee Repo

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.github2gitee }}
        with:
          source-repo: "git@github.com:3cChange/test.git"
          destination-repo: "git@gitee.com:c3Change/test.git"
